package dev.EfraGroup.formulaRacing.Round;

public enum RoundType {
    PRACTICE,
    QUALIFICATION,
    ELIMINATION,
    FINAL,
    SPRINT_QUALIFICATION,
    SPRINT_RACE,
    HOT_POTATO,
    MUSICAL_CHAIR,
    CAPTURE_THE_FLAG,
    INFECTION,
    TEAM_ELIMINATION,
    OBSTACLE_RACE,
    SUMO,
    BLIND_RACE,
    MOVING_TARGET,
    TOTAL_CHAOS,
    ROULETTE
}
