name: FormulaRacing
version: ALPHA 0.2
main: dev.EfraGroup.formulaRacing.FormulaRacing
api-version: 1.21
author: EfraGroup
description: Plugin de corrida de formula 1
depend: [ WorldEdit ]
softdepend:
  - DecentHolograms
  - PlayerPoints
commands:
  boat:
    description: Dá um barco ao jogador
    usage: /boat
    aliases: [ b ]
  lonely:
    description: Dá um barco ao jogador
    usage: /lonely
  heat:
    description: Dá um barco ao jogador
    usage: /heat
  round:
    description: Base command for rounds
    usage: /round
  track:
    description: Base command for rounds
    usage: /track
    aliases: [t]
  trackedit:
    usage: /trackedit
    description: Command for editing tracks.
    aliases: [ te, trackeditor ]
  debug:
    description: Comandos de debug
    usage: /debug
  formularacingreload:
    description: Recarrega as configurações do FormulaRacing
    usage: /formularacingreload
    aliases: [ frr, frreload ]
  timetrial:
    description: Começe uma TimeTrial
    usage: /timetrial
    aliases: [ tt, timett ]
  language:
    description: Muda a linguagem do FormulaRacing
    usage: /language
    aliases: [ lang, l]
  reset:
    description: Reseta sua timetrial.
    usage: /reset
  timetrialrandom:
      description: Entra em uma timetrial aleatória.
      usage: /timetrialrandom
      aliases: [ ttr, timetrialr, ttrandom ]
  timetrialcancel:
      description: Entra em uma timetrial aleatória.
      usage: /timetrialcancel
      aliases: [ ttc, timetrialc, ttcancel ]
  voterace:
    description: Entra em uma timetrial aleatória.
    usage: /voterace
    aliases: [ vr ]
  race:
    description: Entra em uma timetrial aleatória.
    usage: /race
  party:
    description: Entra em uma timetrial aleatória.
    usage: /party
    aliases: [ p ]
  duel:
    description: Entra em uma timetrial aleatória.
    usage: /duel
  event:
    description: Base command for Events.
    usage: /event
  camera:
    description: Base command for cameras
    aliases: [ c, cam ]
  formulamario:
   description: Base command for formulamario
   aliases: [ fm, fmario, formulam ]
  formulawolf:
    description: Base command for formulawolf
    aliases: [ fw, fwolf, formulaw ]
  settings:
    description: Base command for settings
    aliases: [ s ]